spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/common?currentSchema=specification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
